baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "my_gohugo-theme"
themesDir = "./themes"
newContentEditor = "nvim"

[taxonomies]
  tag = "tags"
  category = "categories"
